### ISSUE TITLE
memory issue with custom model

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/onediff#140]
Running https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py with https://huggingface.co/nuigurumi/basil_mix on a rtx 3090 24gb

get 
```
sd init time  19.58131170272827 s.
==> function  text_to_image  try to run...
text_to_image  cuda mem before  3637.625  MB
text_to_image  host mem before  10571.0  MB
  0%|                                                                                                                                                                                                  | 0/50 [00:00<?, ?it/s]
terminate called after throwing an instance of 'oneflow::RuntimeException'
  what():  Error: out of memory
Error message from /home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp:209
        OpCallInstructionUtil::Compute(this, instruction): batch_matmul:OpCall:s_compute

  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 209, in Compute
    OpCallInstructionUtil::Compute(this, instruction)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 41, in Compute
    AllocateOutputBlobsMemory(op_call_instruction_policy, allocator, instruction)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 89, in AllocateOutputBlobsMemory
    blob_object->TryAllocateBlobBodyMemory(allocator)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/eager/eager_blob_object.cpp", line 101, in TryAllocateBlobBodyMemory
    allocator->Allocate(&dptr, required_body_bytes)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/bin_allocator.h", line 392, in Allocate
    AllocateBlockToExtendTotalMem(aligned_size)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/bin_allocator.h", line 305, in AllocateBlockToExtendTotalMem
    backend_->Allocate(&mem_ptr, final_allocate_bytes)
Error Type: oneflow.ErrorProto.out_of_memory_error
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 209, in operator()

Error Type: oneflow.ErrorProto.runtime_error
Related Python stack trace:
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/cross_attention.py", line 203, in get_attention_scores
    attention_probs = attention_probs.to(dtype)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/cross_attention.py", line 246, in __call__
    hidden_states = attn.to_out[1](hidden_states)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/cross_attention.py", line 160, in forward
    return self.processor(
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 169, in __call__
    res = self.forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/attention.py", line 326, in forward
    hidden_states = ff_output + hidden_states
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 169, in __call__
    res = self.forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/transformer_2d.py", line 313, in forward
    return Transformer2DModelOutput(sample=output)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 169, in __call__
    res = self.forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 799, in forward
    hidden_states = downsampler(hidden_states)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 169, in __call__
    res = self.forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 536, in forward
    return UNet2DConditionOutput(sample=sample)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 169, in __call__
    res = self.forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/threading.py", line 771, in wait
    *name* is the thread name. By default, a unique name is constructed of
  File "/opt/conda/lib/python3.8/threading.py", line 857, in start
    self._started.wait()
  File "/opt/conda/lib/python3.8/site-packages/tqdm/_monitor.py", line 39, in __init__
    self.start()
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 568, in __new__
    cls.monitor = TMonitor(cls, cls.monitor_interval)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 838, in progress_bar
    return tqdm(total=total, **self._progress_bar_config)
  File "/opt/conda/lib/python3.8/site-packages/onediff/pipeline_stable_diffusion_oneflow.py", line 743, in __call__
    with self.progress_bar(total=num_inference_steps) as progress_bar:
  File "/opt/conda/lib/python3.8/site-packages/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "diffusers/examples/text_to_image_graph_load.py", line 114, in text_to_image
    images = pipe(
  File "diffusers/examples/text_to_image_graph_load.py", line 29, in new_fn
    out = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/threading.py", line 138, in wait

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 60, in _inner_fn

  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 524, in from_pretrained
    cached_folder = snapshot_download(
  File "diffusers/examples/text_to_image_graph_load.py", line 73, in get_pipe
    sd_pipe = StableDiffusionPipeline.from_pretrained(
  File "diffusers/examples/text_to_image_graph_load.py", line 29, in new_fn
    out = fn(*args, **kwargs)
  File "diffusers/examples/text_to_image_graph_load.py", line 77, in _test_sd_graph_save_and_load
    sch, pipe = get_pipe()
  File "diffusers/examples/text_to_image_graph_load.py", line 172, in test_sd_graph_save_and_load
    _test_sd_graph_save_and_load(True, f0 ,f1, f2)
  File "/opt/conda/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/opt/conda/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/opt/conda/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/opt/conda/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/opt/conda/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/conda/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/opt/conda/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/conda/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/opt/conda/lib/python3.8/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/opt/conda/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "diffusers/examples/text_to_image_graph_load.py", line 177, in <module>
    unittest.main()

Aborted (core dumped)
```

Is this lack of GPU memory? and how can I know these limitations

**Comment by NicholasKao1029** [comment]
Works fine with `stabilityai/stable-diffusion-2`

**Comment by NicholasKao1029** [comment]
Another interesting thing is that `[nuigurumi/basil_mix](https://huggingface.co/nuigurumi/basil_mix)` worked with `oneflow-fork` version of the `graph_load` on same machine.

https://github.com/Oneflow-Inc/diffusers/blob/oneflow-fork/tests/test_pipelines_oneflow_graph_load.py

**Comment by strint** [comment]
It seems that an OOM of Cuda occurs in eager execution.

You can try  https://huggingface.co/nuigurumi/basil_mix with this eager script to check eager execution: https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image.py

**Comment by NicholasKao1029** [comment]
Thanks I'll try that tmrw

**Comment by NicholasKao1029** [comment]
thank you this example works, for `eager` vs not, is this configurable for pre-compiled graphs. 

Basically why I want to use https://github.com/Oneflow-Inc/diffusers/blob/oneflow-fork/tests/test_pipelines_oneflow_graph_load.py is for loading speed.

**Comment by Hank0626** [comment]
> thank you this example works, for `eager` vs not, is this configurable for pre-compiled graphs.
> 
> Basically why I want to use https://github.com/Oneflow-Inc/diffusers/blob/oneflow-fork/tests/test_pipelines_oneflow_graph_load.py is for loading speed.

Could you please type
```
python3 -m oneflow --doctor
```
to show your oneflow and cuda version?

**Comment by Hank0626** [comment]
> 

It works for me if changing the size from 1024 to 512 (in line [137](https://github.com/Oneflow-Inc/diffusers/blob/2af6fafc47b90ad86c0e8b762a3f560ef89eec07/examples/text_to_image_graph_load.py#L135)):
```
size = [512]
```

**Comment by NicholasKao1029** [comment]
> > thank you this example works, for `eager` vs not, is this configurable for pre-compiled graphs.
> > Basically why I want to use https://github.com/Oneflow-Inc/diffusers/blob/oneflow-fork/tests/test_pipelines_oneflow_graph_load.py is for loading speed.
> 
> Could you please type
> 
> ```
> python3 -m oneflow --doctor
> ```
> 
> to show your oneflow and cuda version?

```
path: ['/opt/conda/lib/python3.8/site-packages/oneflow']
version: 0.9.1.dev20230305+cu117
git_commit: df78864a
cmake_build_type: Release
rdma: True
mlir: True
```

**Comment by NicholasKao1029** [comment]
> > 
> 
> It works for me if changing the size from 1024 to 512 (in this [line](https://github.com/Oneflow-Inc/diffusers/blob/2af6fafc47b90ad86c0e8b762a3f560ef89eec07/examples/text_to_image_graph_load.py#L135)):
> 
> ```
> size = [512]
> ```

Interesting, where does this variation come from comparing `sd2` vs the custom model

**Comment by strint** [comment]
> > > 
> > 
> > 
> > It works for me if changing the size from 1024 to 512 (in this [line](https://github.com/Oneflow-Inc/diffusers/blob/2af6fafc47b90ad86c0e8b762a3f560ef89eec07/examples/text_to_image_graph_load.py#L135)):
> > ```
> > size = [512]
> > ```
> 
> Interesting, where does this variation come from comparing `sd2` vs the custom model

Dose `size = [512]` work for you?

It's probably that there is a memory cost increase in the new version, we will investigate this.

**Comment by NicholasKao1029** [comment]
It solves the memory issue it seems but anther issue arrises

```
F
======================================================================
FAIL: test_sd_graph_save_and_load (__main__.OneFlowPipeLineGraphSaveLoadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "examples/text_to_image_graph_load.py", line 172, in test_sd_graph_save_and_load
    _test_sd_graph_save_and_load(True, f0 ,f1, f2)
  File "examples/text_to_image_graph_load.py", line 143, in _test_sd_graph_save_and_load
    assert np.abs(no_g_images[img_idx] - with_g_images[img_idx]).mean() < 1e-2
AssertionError
```
I think this is based on `with_graph` vs `not_with_graph` perf
