### ISSUE TITLE
Support for Lora in oneflow diffusers

### ISSUE THREAD

**Issue by abi98213** [Oneflow-Inc/onediff#154]
Hello,
Is it possible to get support for loading lora trained models in diffusers of oneflow ?
Thanks

**Comment by jackalcooper** [comment]
yes, its possible.with diffusers 0.12 there is lora support

**Comment by neptune4year** [comment]
Hi, I run the latest version oneflow-diffusers on lora model, but it failed. Please help to check what's the problem.

The  error info is below:
libibverbs not available, ibv_fork_init skipped
/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/diffusers/configuration_utils.py:195: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_dpmsolver_multistep.DPMSolverMultistepScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
[ERROR](GRAPH:UNetGraph_0:UNetGraph) building graph got error.
Traceback (most recent call last):
  File "demo.py", line 23, in <module>
    images = pipe(prompt, num_inference_steps=20).images
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/onediff/pipeline_stable_diffusion_oneflow.py", line 736, in __call__
    unet_graph.compile(latent_model_input, t, text_embeddings)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/onediff/oneflow_graph_compile_cache.py", line 33, in compile
    self.graph_._compile(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 848, in _compile
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 1209, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 1324, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/onediff/pipeline_stable_diffusion_oneflow.py", line 47, in build
    return self.unet(
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 582, in forward
    sample, res_samples = downsample_block(
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 837, in forward
    hidden_states = attn(
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/diffusers/models/attention.py", line 291, in forward
    attn_output = self.attn1(
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/diffusers/models/cross_attention.py", line 205, in forward
    return self.processor(
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/weichen/miniconda3/envs/oneflow/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 193, in forward
    raise NotImplementedError()
NotImplementedError

My code is below:
import oneflow as flow

flow.mock_torch.enable()
from diffusers import DPMSolverMultistepScheduler
from onediff import OneFlowStableDiffusionPipeline

model_id = "runwayml/stable-diffusion-v1-5"

dpm_solver = DPMSolverMultistepScheduler.from_config(model_id, subfolder="scheduler")

pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    model_id,
    use_auth_token=True,
    revision="fp16",
    torch_dtype=flow.float16,
    scheduler=dpm_solver
)
pipe.unet.load_attn_procs("/path/to/lora")
pipe = pipe.to("cuda:7")

prompt = "a photo of an astronaut riding a horse on mars"
with flow.autocast("cuda"):
    images = pipe(prompt, num_inference_steps=20).images
    for i, image in enumerate(images):
        image.save(f"{prompt}-of-{i}.png")

**Comment by NicholasKao1029** [comment]
Was this ever figured out?

**Comment by strint** [comment]
Please update to the latest version: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
