### ISSUE TITLE
Improving performance on model switch 

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/onediff#177]
Is there a way to improve performance on model switch?

Eg
```
pipe.from_pretrained("./a") 
pipe.load_graph("./a_graph") 

# first image is quite expensive, need to load graph?
# subsequent images are cheap

another_pipe.from_pretrained("./b") # pipe loaded from `something/B`
another_pipe.load_graph("./b_graph")

# first image is quite expensive, need to load graph?
# subsequent images are cheap
```

I compare this to changing dimensions for the same pipe, where the `cache` is utilized and no time at all is taken to switch between those graphs. 

How do I improve performance here?

I see that the cache bucket is emptied when switching models, is there a way to preserve this?

**Comment by NicholasKao1029** [comment]
How does graph_save and graph_load work, as in my tests it's very cheap to actually `load_graph` on a different model basically ~0secs. But still get the perf hit on the first request. 

But this perf hit on first request is the same thing that happens when I don't use `graph_load`

**Comment by Hank0626** [comment]
We have recently made some changes to graph save and load, which you can check out in the latest main branch. The function of `graph_save` is to store the compiled graph at a user-specified path, while `graph_load` reads the graph from the path and stores it in a dictionary called graph_dict. When the pipe generates images, it directly takes the compiled graph from graph_dict, thus improving performance. (cache bucket is not used anymore)

**Comment by NicholasKao1029** [comment]
thats fantastic and what I had expected. I will pull from main branch and try it out

**Comment by NicholasKao1029** [comment]
I installed the latest branch via 
`pip install git+https://github.com/Oneflow-Inc/diffusers`

having a problem with `graph_load` because it seems `graph_save` does not output anything.

looking at `graph_save` code, it iterates through `self.graph_dict.items()` but when printing `pipe.graph_dict` it comes out as `{}` so nothing is ever saved. 

More over when I do pipe(...) to create an image and have `compile_unet=True` or compile_vae=True`  I get this error
```
  0%|                                                                                                                                                                                                                                  | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "setup.py", line 308, in <module>
    setup(model_id=model)
  File "setup.py", line 214, in setup
    save_compiled_graphs(pipe, model_id, sizes_to_save)
  File "setup.py", line 100, in save_compiled_graphs
    dumy_text_to_image(pipe, size, True)
  File "setup.py", line 71, in dumy_text_to_image
    images = pipe(
  File "/opt/conda/lib/python3.8/site-packages/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/onediff/pipeline_stable_diffusion_oneflow.py", line 702, in __call__
    noise_pred = unet_graph(latent_model_input, t, text_embeddings)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 268, in __call__
    return self._dynamic_input_graph_cache(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/cache.py", line 113, in __call__
    graph = self.get_graph(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/cache.py", line 213, in get_graph
    graph = self._init_and_get_a_graph_in_cache(cache_key)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/cache.py", line 157, in _init_and_get_a_graph_in_cache
    graph.enable_shared()
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 859, in enable_shared
    assert (
AssertionError:  enable_shared must be set before graph compile.
```

however if I print out `pipe.enable_compile` it outputs True, and it looks like it's the internal `unet` that has it `False`

**Comment by Hank0626** [comment]
Could you provide your oneflow version？
```
python -m oneflow --doctor
```

**Comment by Hank0626** [comment]
Could you please provide a portion of your code so that I can better identify the error?

**Comment by NicholasKao1029** [comment]
Doctor info
```
W20230410 17:21:04.280611  5560 cuda_device_descriptor_class.cpp:48] CUDA driver version is insufficient for CUDA runtime version
path: ['/opt/conda/lib/python3.8/site-packages/oneflow']
version: 0.9.1.dev20230409+cu117
git_commit: c19d148
cmake_build_type: Release
rdma: True
mlir: True
```

**Comment by NicholasKao1029** [comment]
I had to create a new runpod instance and the issue with calling the `pipe` was fixed and so the unet and vae were both compiled!

However there is now a different issue switching between different models I'll provide details below

**Comment by NicholasKao1029** [comment]
This is the error 
```
F20230410 19:18:11.085217 16070 buffer_manager.h:31] Check failed: name2buffer_.emplace(buffer_name, std::make_unique<Buffer<T>>(buffer_size)).second
*** Check failure stack trace: ***
    @     0x7f7526fd1ada  google::LogMessage::Fail()
    @     0x7f7526fd4a11  google::LogMessage::SendToLog()
    @     0x7f7526fd1609  google::LogMessage::Flush()
    @     0x7f7526fd52f9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f751ec19b2f  oneflow::BufferMgr<>::NewBuffer()
    @     0x7f751ebf769a  oneflow::NNGraph::NewRuntimeBuffers()
    @     0x7f751ec12a5a  oneflow::NNGraph::InitRuntime()
    @     0x7f761181ed03  (unknown)
    @     0x7f761168865a  (unknown)
    @     0x564b89d60e7e  PyCFunction_Call
    @     0x564b89d49631  _PyObject_MakeTpCall
    @     0x564b89d60bfd  method_vectorcall
    @     0x564b89d44ffc  _PyEval_EvalFrameDefault
    @     0x564b89d3fb76  _PyEval_EvalCodeWithName
    @     0x564b89d6085c  method_vectorcall
    @     0x564b89d44ffc  _PyEval_EvalFrameDefault
    @     0x564b89d512a6  _PyFunction_Vectorcall
    @     0x564b89d40d9d  _PyEval_EvalFrameDefault
    @     0x564b89d3fb76  _PyEval_EvalCodeWithName
    @     0x564b89d6085c  method_vectorcall
    @     0x564b89d44ffc  _PyEval_EvalFrameDefault
    @     0x564b89d3f461  _PyEval_EvalCodeWithName
    @     0x564b89d6085c  method_vectorcall
    @     0x564b89d41808  _PyEval_EvalFrameDefault
    @     0x564b89d3f461  _PyEval_EvalCodeWithName
    @     0x564b89d5133c  _PyFunction_Vectorcall
    @     0x564b89d40aab  _PyEval_EvalFrameDefault
    @     0x564b89d512a6  _PyFunction_Vectorcall
    @     0x564b89d40aab  _PyEval_EvalFrameDefault
    @     0x564b89d512a6  _PyFunction_Vectorcall
    @     0x564b89d63172  PyObject_Call
    @     0x564b89d42870  _PyEval_EvalFrameDefault
[2023-04-10 19:18:11 +0000] [16068] [WARNING] Worker with pid 16070 was terminated due to signal 6
[2023-04-10 19:18:11 +0000] [16293] [INFO] Booting worker with pid: 16293
```

**Comment by NicholasKao1029** [comment]
This is a route for my webserver
```
def txt2img_dumb(request):
    data = request
    try:
        start_time = time.time()
        prompt = data['prompt']
        negative_prompt = data['negprompt']
        image_height = data['height']
        image_width = data['width']
        scheduler = data['scheduler']
        steps = data['steps']
        cfg = data['cfg']
        seed = data['seed']
        num_images = data['num_images']
        # vae = data['vae']
        model = data.get('model_id', None) or model_id
        print('model retrieved ' + model)
        pipe = get_pipe_for_model_and_size(model, (image_width, image_height)) # BREAKS HERE
        ....
```

This is the pipe swap out logic, basically retrieves the pipe, based on the model_id and size

```
def get_pipe_for_model_and_size(model_id, size, path_manager=path_manager):
    """
    Returns the appropriate pipe based on the model_id and size parameters.

    :param model_id: The model ID for the desired pipe.
    :param size: A tuple representing the desired size, e.g. (512, 512). `(<width>, <height>)`
    :param path_manager: An instance of GraphPathManager.
    :return: The pipe instance for the given model_id and size.
    """
    global current_pipe, current_pipe_info
    start_time = time.time()

    # Check if the current pipe matches the requested model_id and size
    if (current_pipe is not None and current_pipe_info['model_id'] == model_id
            and current_pipe_info['size'] == size):
        print(f"Time taken to return cached pipe: {time.time() - start_time:.2f} seconds")
        return current_pipe

    # Get the graph path for the specified model_id and size
    compile_unet = False
    try:
        graph_path, pipe_path = path_manager.get(model_id, size)
    except Exception as e:
        print('could not get path for model id and size request')
        return current_pipe

    if current_pipe == None or model_id != current_pipe_info["model_id"]:
        current_pipe = setup_pipe(id=pipe_path)
        compile_unet = True
        print(f"Time taken to setup pipe from pipe path: {time.time() - start_time:.2f} seconds")

    start_time = time.time()
    print(graph_path, pipe_path)
    current_pipe.load_graph(graph_path, compile_unet=compile_unet, compile_vae=False) # BREAKS HERE
    print(f"Time taken to load graph: {time.time() - start_time:.2f} seconds")
    current_pipe.to("cuda")

    # Update current_pipe_info with the new model_id and size
    current_pipe_info['model_id'] = model_id
    current_pipe_info['size'] = size

    return current_pipe
```

**Comment by NicholasKao1029** [comment]
This looks like as @strint pointed out in an earlier comment 
| Please refer to this issue: https://github.com/Oneflow-Inc/oneflow/issues/9898

But I'm a novice with processes, is there a straight forward way of doing this?

**Comment by NicholasKao1029** [comment]
Another thing is I tried not switching out `pipe(id=pipe_path)` and just loading a different compiled `graph_path` basically it seems the model doesn't change is this as expected? or  is this undefined behaviour

**Comment by strint** [comment]
> buffer_manager.h:31] Check failed: name2buffer_.emplace(buffer_name, std::make_unique<Buffer<T>>(buffer_size)).second

This means that there are graphs having the same graph name in current process.

Did you try to save and load graph in the same process or load same graph multiple times?

**Comment by NicholasKao1029** [comment]
> > buffer_manager.h:31] Check failed: name2buffer_.emplace(buffer_name, std::make_unique<Buffer>(buffer_size)).second
> 
> This means that there are graphs having the same graph name in current process.
> 
> Did you try to save and load graph in the same process or load same graph multiple times?

Save is done in by a script before the webserver starts up.
model A will be under `./path/to/A/unet` `./path/to/A/vae` 
model B will be similarly `./path/to/B/unet` `./path/to/B/vae` 
is this what you mean by the name is the same as in unet and vae are same names although different paths.

When the server gets a request it will determine what `graph` and `pipe` to load based on the API parameters. 

1. request for Model A
2. request for Model B
- now needs to change pipes and it will change based on this code 
```
def get_pipe_for_model_and_size(model_id, size, path_manager=path_manager):
    """
    Returns the appropriate pipe based on the model_id and size parameters.

    :param model_id: The model ID for the desired pipe.
    :param size: A tuple representing the desired size, e.g. (512, 512). `(<width>, <height>)`
    :param path_manager: An instance of GraphPathManager.
    :return: The pipe instance for the given model_id and size.
    """
    global current_pipe, current_pipe_info
    start_time = time.time()

    # Check if the current pipe matches the requested model_id and size
    if (current_pipe is not None and current_pipe_info['model_id'] == model_id
            and current_pipe_info['size'] == size):
        print(f"Time taken to return cached pipe: {time.time() - start_time:.2f} seconds")
        return current_pipe

    # Get the graph path for the specified model_id and size
    compile_unet = False
    try:
        graph_path, pipe_path = path_manager.get(model_id, size)
    except Exception as e:
        print('could not get path for model id and size request')
        return current_pipe

    if current_pipe == None or model_id != current_pipe_info["model_id"]:
        current_pipe = setup_pipe(id=pipe_path)
        compile_unet = True
        print(f"Time taken to setup pipe from pipe path: {time.time() - start_time:.2f} seconds")

    start_time = time.time()
    print(graph_path, pipe_path)
    current_pipe.load_graph(graph_path, compile_unet=compile_unet, compile_vae=False) # BREAKS HERE
    print(f"Time taken to load graph: {time.time() - start_time:.2f} seconds")
    current_pipe.to("cuda")

    # Update current_pipe_info with the new model_id and size
    current_pipe_info['model_id'] = model_id
    current_pipe_info['size'] = size

    return current_pipe
```

**Comment by Hank0626** [comment]
this example works for me
```python
import os
from onediff import OneFlowStableDiffusionPipeline
import time
import oneflow as flow
import gc
flow.mock_torch.enable()
pipe_file_path = "./pipe1"                   # pipe1 save path
graph_save_path = "./graph1"                   # graph1 save path
pipe_file_path1 = "./pipe2"                   # pipe2 save path
graph_save_path1 = "./graph2"                   # graph2 save path
DIM = 512
prompt = "a photo of an astronaut riding a horse on mars"
cur_generator = flow.Generator("cuda").manual_seed(1024)
pipe = None
def tearDown():
    gc.collect()
    flow.cuda.empty_cache()

def run_save_graph(pipe_file_path, graph_save_path):
    os.makedirs(pipe_file_path, exist_ok=True)
    os.makedirs(graph_save_path, exist_ok=True)
    print("Running grave save...")
    pipe = OneFlowStableDiffusionPipeline.from_pretrained(
        "stabilityai/stable-diffusion-2",
        revision="fp16",
        torch_dtype=flow.float16,
    )
    pipe = pipe.to("cuda")
    pipe.set_graph_compile_cache_size(9)
    pipe.enable_graph_share_mem()

    start = time.time()
    images = pipe(
        prompt,
        height=DIM,
        width=DIM,
        compile_unet=True,
        compile_vae=False,
        generator=cur_generator,
        output_type="np",
    ).images
    pipe.save_pretrained(pipe_file_path)
    pipe.save_graph(graph_save_path)
    print(f"Time cost (save): {time.time() - start:.2f}s")


def run_load_graph(pipe_file_path, graph_save_path):
    global pipe
    print("Running grave load...")
    pipe = OneFlowStableDiffusionPipeline.from_pretrained(
        pipe_file_path,
        revision="fp16",
        torch_dtype=flow.float16,
    )

    pipe = pipe.to("cuda")
    pipe.set_graph_compile_cache_size(9)

    pipe.load_graph(
        graph_save_path, compile_unet=True, compile_vae=False, time_flag=True
    )

    start = time.time()
    images = pipe(
        prompt,
        height=DIM,
        width=DIM,
        compile_unet=True,
        compile_vae=False,
        generator=cur_generator,
        output_type="np",
    ).images

    print(f"Time cost: {time.time() - start:.2f}s")


if __name__ == "__main__":
    if not os.path.exists(pipe_file_path):
        run_save_graph(pipe_file_path, graph_save_path)
    if not os.path.exists(pipe_file_path1):
        run_save_graph(pipe_file_path1, graph_save_path1)
    run_load_graph(pipe_file_path, graph_save_path)
    run_load_graph(pipe_file_path1, graph_save_path1)
```

**Comment by Hank0626** [comment]
`compile_unet` refers to the switch for compiling the computation graph of Unet. When set to "true", the static graph of Unet will be compiled, accelerating the inference speed for subsequent computations. Additionally, saving the compiled static graph using `save_graph` and subsequently loading it will further speed up the inference process. Similarly, `compile_vae` works in the same way but is specific to VAE.

**Comment by NicholasKao1029** [comment]
loading a saved graph - increase in speed
loading a saved graph, then using `compile_unet` - larger increase in speed
 
Is this correct

**Comment by NicholasKao1029** [comment]
> this little example works for me.
> 
> ```python
> import os
> from onediff import OneFlowStableDiffusionPipeline
> import time
> import oneflow as flow
> import gc
> flow.mock_torch.enable()
> pipe_file_path = "./pipe1"                   # pipe1 save path
> graph_save_path = "./graph1"                   # graph1 save path
> pipe_file_path1 = "./pipe2"                   # pipe2 save path
> graph_save_path1 = "./graph2"                   # graph2 save path
> DIM = 512
> prompt = "a photo of an astronaut riding a horse on mars"
> cur_generator = flow.Generator("cuda").manual_seed(1024)
> pipe = None
> 
> def run_save_graph(pipe_file_path, graph_save_path):
>     os.makedirs(pipe_file_path, exist_ok=True)
>     os.makedirs(graph_save_path, exist_ok=True)
>     print("Running grave save...")
>     pipe = OneFlowStableDiffusionPipeline.from_pretrained(
>         "stabilityai/stable-diffusion-2",
>         revision="fp16",
>         torch_dtype=flow.float16,
>     )
>     pipe = pipe.to("cuda")
>     pipe.set_graph_compile_cache_size(9)
>     pipe.enable_graph_share_mem()
> 
>     start = time.time()
>     images = pipe(
>         prompt,
>         height=DIM,
>         width=DIM,
>         compile_unet=True,
>         compile_vae=False,
>         generator=cur_generator,
>         output_type="np",
>     ).images
>     pipe.save_pretrained(pipe_file_path)
>     pipe.save_graph(graph_save_path)
>     print(f"Time cost (save): {time.time() - start:.2f}s")
> 
> 
> def run_load_graph(pipe_file_path, graph_save_path):
>     global pipe
>     print("Running grave load...")
>     pipe = OneFlowStableDiffusionPipeline.from_pretrained(
>         pipe_file_path,
>         revision="fp16",
>         torch_dtype=flow.float16,
>     )
> 
>     pipe = pipe.to("cuda")
>     pipe.set_graph_compile_cache_size(9)
> 
>     pipe.load_graph(
>         graph_save_path, compile_unet=True, compile_vae=False
>     )
> 
>     start = time.time()
>     images = pipe(
>         prompt,
>         height=DIM,
>         width=DIM,
>         compile_unet=True,
>         compile_vae=False,
>         generator=cur_generator,
>         output_type="np",
>     ).images
> 
>     print(f"Time cost: {time.time() - start:.2f}s")
> 
> 
> if __name__ == "__main__":
>     if not os.path.exists(pipe_file_path):
>         run_save_graph(pipe_file_path, graph_save_path)
>     if not os.path.exists(pipe_file_path1):
>         run_save_graph(pipe_file_path1, graph_save_path1)
>     run_load_graph(pipe_file_path, graph_save_path)
>     run_load_graph(pipe_file_path1, graph_save_path1)
> ```

This didn't work for me running `python graph_example.py`
```
W20230411 23:15:59.793354  6566 cuda_stream.cpp:48] Runtime version 8.4 of cuDNN incompatible with compiletime version 8.5.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 11.59it/s]
Time cost (save): 34.36s
Running grave save...
Fetching 12 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 17254.59it/s]
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:

pip install accelerate

.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 42.09it/s]
Time cost (save): 29.88s
Running grave load...
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:

pip install accelerate

.
F20230411 23:17:15.600050  6429 buffer_manager.h:31] Check failed: name2buffer_.emplace(buffer_name, std::make_unique<Buffer<T>>(buffer_size)).second
*** Check failure stack trace: ***
    @     0x7f4515870ada  google::LogMessage::Fail()
    @     0x7f4515873a11  google::LogMessage::SendToLog()
    @     0x7f4515870609  google::LogMessage::Flush()
    @     0x7f45158742f9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f450d4b4e3f  oneflow::BufferMgr<>::NewBuffer()
    @     0x7f450d49298a  oneflow::NNGraph::NewRuntimeBuffers()
    @     0x7f450d4add4a  oneflow::NNGraph::InitRuntime()
    @     0x7f4601384a23  (unknown)
    @     0x7f46011ee65a  (unknown)
    @     0x5619f682ce7e  PyCFunction_Call
    @     0x5619f6815631  _PyObject_MakeTpCall
    @     0x5619f682cbfd  method_vectorcall
    @     0x5619f6810ffc  _PyEval_EvalFrameDefault
    @     0x5619f680bb76  _PyEval_EvalCodeWithName
    @     0x5619f682c85c  method_vectorcall
    @     0x5619f6810ffc  _PyEval_EvalFrameDefault
    @     0x5619f681d2a6  _PyFunction_Vectorcall
    @     0x5619f680cd9d  _PyEval_EvalFrameDefault
    @     0x5619f680bb76  _PyEval_EvalCodeWithName
    @     0x5619f682c85c  method_vectorcall
    @     0x5619f6810ffc  _PyEval_EvalFrameDefault
    @     0x5619f680b461  _PyEval_EvalCodeWithName
    @     0x5619f682c85c  method_vectorcall
    @     0x5619f680d808  _PyEval_EvalFrameDefault
    @     0x5619f681d2a6  _PyFunction_Vectorcall
    @     0x5619f680caab  _PyEval_EvalFrameDefault
    @     0x5619f680b461  _PyEval_EvalCodeWithName
    @     0x5619f68cade9  PyEval_EvalCodeEx
    @     0x5619f68cadab  PyEval_EvalCode
    @     0x5619f68eb903  run_eval_code_obj
    @     0x5619f68ea8e3  run_mod
    @     0x5619f678af2f  pyrun_file
Aborted (core dumped)
```

**Comment by NicholasKao1029** [comment]
hmm do you mean 
run the script once - it breaks 
run it second time - should work 

because it seems to break on second time for me as well :/

doctor
```
path: ['/opt/conda/lib/python3.8/site-packages/oneflow']
version: 0.9.1.dev20230411+cu117
git_commit: 62680a3d
cmake_build_type: Release
rdma: True
mlir: True
```

**Comment by Hank0626** [comment]
I try it again on my machine, it's ok though. weired. Are you sure you didn't run `run_save_graph` on the second time?

**Comment by NicholasKao1029** [comment]
you are right it works! 

so this means if I try to do 

pipe1 request 
pipe2 request 
pipe1 request (this will break) 

What can be done for this then

**Comment by Hank0626** [comment]
Why do you want to request for pipe1 again? If you have load the graph of pipe 1, you can directly use it to inference

**Comment by NicholasKao1029** [comment]
ohh like save it in another variable, you are right I will just switch out my interface for that

**Comment by NicholasKao1029** [comment]
> Why do you want to request for pipe1 again? If you have load the graph of pipe 1, you can directly use it to inference

Sorry I seem to have a misunderstanding of this could you provide a code snippet forwhat you mean?

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
