### ISSUE TITLE
pytorch version problem after using flow.mock_torch.enable()

### ISSUE THREAD

**Issue by AppleAndBanana** [Oneflow-Inc/onediff#245]
This work is very exciting, but when I try oneflow with diffusers with https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion (Without Docker),  I got error below:

python3 -m onediff.demo
Traceback (most recent call last):
  File "/opt/conda/envs/py3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/envs/py3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/envs/py3.10/lib/python3.10/site-packages/onediff/__init__.py", line 21, in <module>
    import diffusers
  File "/opt/conda/envs/py3.10/lib/python3.10/site-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/opt/conda/envs/py3.10/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/opt/conda/envs/py3.10/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "/opt/conda/envs/py3.10/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 20, in <module>
    from .import_utils import is_accelerate_available
  File "/opt/conda/envs/py3.10/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 225, in <module>
    raise ValueError("PyTorch should be >= 1.12")
ValueError: PyTorch should be >= 1.12

I am pretty sure my torch version is '2.0.0+cu117', and the same error occurs after I reinstall torch1.13.
Any ideas?

**Comment by Chris-Ski** [comment]
Same,

Trying to get this to work for the past 3 days :( I did a fresh install of Ubuntu 20.04 , and tried Python 3.8 and 3.10 nothing worked :( ... please help.... 

Dont matter what I done, I have same comunicat: 

Traceback (most recent call last):
  File "examples/text_to_image.py", line 1, in <module>
    from onediff import OneFlowStableDiffusionPipeline
  File "/usr/local/lib/python3.8/dist-packages/onediff/__init__.py", line 20, in <module>
    flow.mock_torch.enable(lazy=True)
**TypeError: __init__() got an unexpected keyword argument 'lazy'**


Graphic Card RTX 3070
Cuda 11.7
Drivers 515.43.04

Oneflow installed : python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117
"torch" "transformers==4.27.1" "diffusers[torch]==0.15.1" 

![Screenshot from 2023-08-28 13-36-34](https://github.com/Oneflow-Inc/diffusers/assets/104285717/ff777519-1d03-472f-aea1-8f2fb3fff682)
![Screenshot from 2023-08-28 13-36-34 (another copy)](https://github.com/Oneflow-Inc/diffusers/assets/104285717/bbf0d9ef-d1c0-4742-b173-3936709c85fb)
![Screenshot from 2023-08-28 13-36-34 (copy)](https://github.com/Oneflow-Inc/diffusers/assets/104285717/5578f296-87fe-4e19-9acb-0b3a6794bc50)
![Screenshot from 2023-08-28 13-45-51](https://github.com/Oneflow-Inc/diffusers/assets/104285717/6aa84a8c-b84e-4807-9f92-9cbd759b1786)

any idea whats wrong ??

**Comment by hx173149** [comment]
I have got the same error!
And I changed many version of oneflow/onediff/diffusers, it still not work!

**Comment by jackalcooper** [comment]
the latest version of one diff is no longer using mock. please check out the latest wiki

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
