### ISSUE TITLE
(GRAPH:UNetGraph_0:UNetGraph) building graph got error.

### ISSUE THREAD

**Issue by zhangjun** [Oneflow-Inc/onediff#263]
Any solutions for this?

I run ```oneflow_compile(model.unet)``` in my project, and get this error.
I have changed Attention using ```set_attn_processor()```
```python
[ERROR](GRAPH:UNetGraph_0:UNetGraph) building graph got error.
  0%|                                                                                                                 | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/zhangjun/oneflow/test/main.py", line 109, in <module>
    main()
  File "/zhangjun/oneflow/test/main.py", line 92, in main
    im = model(tgt_prompt, negative_prompt=neg_prompt, generator=torch.manual_seed(seed), width=width, height=height, num_inference_steps=num_inference_steps).images
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 680, in __call__
    noise_pred = self.unet(
  File "/zhangjun/git/oneflow-diffusers/src/onediff/infer_compiler/with_oneflow_compile.py", line 98, in __call__
    output = self._dpl_graph(*mapped_args, **mapped_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 278, in __call__
    return self._dynamic_input_graph_cache(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 115, in __call__
    return graph(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 281, in __call__
    self._compile(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 849, in _compile
    return self._compile_new(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 868, in _compile_new
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1322, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1439, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/zhangjun/git/oneflow-diffusers/src/onediff/infer_compiler/with_oneflow_compile.py", line 45, in build
    pred = self.unet(
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 237, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 956, in forward
    sample, res_samples = downsample_block(
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 237, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 1086, in forward
    hidden_states = attn(
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 237, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 315, in forward
    hidden_states = block(
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 237, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/attention.py", line 197, in forward
    attn_output = self.attn1(
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    unbound_forward_of_module_instance = self.to(Module).forward.__func__
AttributeError: 'function' object has no attribute '__func__'. Did you mean: '__doc__'?
```

**Comment by jackalcooper** [comment]
could you run `python3 -m oneflow --doctor` to check it is nightly oneflow?

**Comment by zhangjun** [comment]
> could you run `python3 -m oneflow --doctor` to check it is nightly oneflow?

```python
path: ['/opt/conda/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20230918+cu117
git_commit: b93d13f
cmake_build_type: Release
rdma: True
mlir: True
```

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
