### ISSUE TITLE
Fail to run onediff container

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/onediff#265]
```py
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/src/onediff/src/onediff/demo/__main__.py", line 5, in <module>
    import oneflow as flow
  File "/usr/local/lib/python3.10/dist-packages/oneflow/__init__.py", line 288, in <module>
    import oneflow.framework.register_class_method_util as register_class_method_util
  File "/usr/local/lib/python3.10/dist-packages/oneflow/framework/register_class_method_util.py", line 17, in <module>
    import oneflow.framework.check_point_v2 as check_point_v2
  File "/usr/local/lib/python3.10/dist-packages/oneflow/framework/check_point_v2.py", line 49, in <module>
    import oneflow.nn.graph.graph as graph_util
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/__init__.py", line 17, in <module>
    from oneflow.nn.graph import Graph
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/__init__.py", line 16, in <module>
    from .graph import Graph
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 33, in <module>
    import oneflow.framework.graph_build_util as graph_build_util
  File "/usr/local/lib/python3.10/dist-packages/oneflow/framework/graph_build_util.py", line 30, in <module>
    from oneflow.nn.graph.proxy import GraphBlockType
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/proxy.py", line 28, in <module>
    from oneflow.nn.graph.graph_block import (
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph_block.py", line 23, in <module>
    from oneflow.nn.graph.util import (
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/util.py", line 271, in <module>
    ops: protobuf.pyext._message.RepeatedCompositeContainer,
AttributeError: module 'google.protobuf' has no attribute 'pyext'
```
https://github.com/protocolbuffers/protobuf/issues/13300

**Comment by strint** [comment]
Fixed with: https://github.com/Oneflow-Inc/oneflow/pull/10336
