### ISSUE TITLE
Inferring text_to_image_sdxl.py error

### ISSUE THREAD

**Issue by l-dawei** [Oneflow-Inc/onediff#271]
When I try to run text_to_image_sdxl.py, I encountered the following error:

`(oneflow) [dawei.liu()@node15 examples]$ python text_to_image_sdxl.py --compile
Traceback (most recent call last):
  File "text_to_image_sdxl.py", line 15, in <module>
    from onediff.infer_compiler import oneflow_compile
  File "/oss/comicai/dawei.liu/T2I/diffusers/src/onediff/infer_compiler/__init__.py", line 4, in <module>
    from .with_oneflow_compile import oneflow_compile
  File "/oss/comicai/dawei.liu/T2I/diffusers/src/onediff/infer_compiler/with_oneflow_compile.py", line 1, in <module>
    from . import obj_1f_from_torch
  File "/oss/comicai/dawei.liu/T2I/diffusers/src/onediff/infer_compiler/obj_1f_from_torch.py", line 14, in <module>
    def __init_of_mds(package_names: list[str]):
TypeError: 'type' object is not subscriptable`

The versions of my oneflow and onediff are as follows：
onediff                  0.11.0.dev0             /oss/comicai/dawei.liu/T2I/diffusers/src
oneflow                  0.9.1.dev20231008+cu117

Could you help me? Thanks a lot.

**Comment by doombeaker** [comment]
can you post your python version, is it newer than 3.10?

**Comment by l-dawei** [comment]
> can you post your python version, is it newer than 3.10?

Python 3.8.0

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
