### ISSUE TITLE
Custom Schedulers cannot be changed at runtime

### ISSUE THREAD

**Issue by chavinlo** [Oneflow-Inc/onediff#96]
### Describe the bug

They simply can't. I am following the example provided in the Wiki.

### Reproduction

I have tried loading the scheduler like this:

`diffusers.OneFlowDPMSolverMultistepScheduler.from_config(sch_source, subfolder="scheduler", algorithm_type="dpmsolver")`

following the example on the Wiki

then, passing it to the pipe like this:

```
  if scheduler in schedulers:
      scheduler_obj = schedulers[scheduler]
      scheduler_obj.set_timesteps(steps, device=device)
      #scheduler_obj is a OneFlowDPMSolverMultistepScheduler object.
  else:
      imgq('fail', f'scheduler {scheduler} not found')
      continue
  with torch.autocast("cuda"):
      pipe.scheduler = scheduler_obj
      image = pipe(
          prompt=prompt,
          num_inference_steps=steps,
          guidance_scale=cfg,
          negative_prompt=negative_prompt,
          height=image_height,
          width=image_width,
          generator=torch.Generator().manual_seed(seed)
      )[0][0]
```

### Logs

```shell
Traceback (most recent call last):
  File "/workspace/node/threads/base.py", line 77, in image_generator
    image = pipe(
  File "/workspace/env/lib/python3.10/site-packages/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/workspace/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py", line 676, in __call__
    noise_pred = unet_graph(latent_model_input, t, text_embeddings)
  File "/workspace/diffusers/src/diffusers/oneflow_graph_compile_cache.py", line 63, in __call__
    return self.graph_(*args, **kwargs)
  File "/workspace/env/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 250, in __call__
    return self.__run(*args, **kwargs)
  File "/workspace/env/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1481, in __run
    oneflow._oneflow_internal.nn.graph.RunLazyNNGraph(
oneflow._oneflow_internal.exception.RuntimeError: Error: nn.Graph ONLY accepts static inputs tensor meta, please check whether your input tensor meta each step is the same as the input of first call graph.
The excepted tensor meta is: shape=(), dtype=oneflow.int64, device=cpu:0, but the actual tensor meta is: shape=(), dtype=oneflow.float64, device=cpu:0. The input index is 1.
```

### System Info

Using OneFlow latest version
Python 3.10.10
Torch 1.13.1
CUDA 12.0
Driver 525.78
A100-SXM4-80GB

**Comment by jackalcooper** [comment]
```
The excepted tensor meta is: shape=(), dtype=oneflow.int64, device=cpu:0, but the actual tensor meta is: shape=(), dtype=oneflow.float64, device=cpu:0. The input index is 1.
```
this error indicates the timestamp's data type varies in the two schedulers. Two workarounds I can think of:
- Call `to(dtype =oneflow.float64)` before compiling `nn.graph`
- change the implementation of the schedulers being used and use only one data type of tilmestep

**Comment by strint** [comment]
Please update to the latest version: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
